complete -c gosearch -l i -d 'case-insensitive matching'
complete -c gosearch -l n -d 'show line numbers'
complete -c gosearch -l w -d 'whole-word matching'
complete -c gosearch -l workers -r -d 'worker pool size'
complete -c gosearch -l max-size -r -d 'max file size'
complete -c gosearch -l extensions -r -d 'extensions list'
complete -c gosearch -l exclude-dir -r -d 'exclude directories'
complete -c gosearch -l count -d 'count only'
complete -c gosearch -l quiet -d 'quiet mode'
complete -c gosearch -l color -d 'color output'
complete -c gosearch -l abs -d 'absolute paths'
complete -c gosearch -l format -r -a 'plain json' -d 'output format'
complete -c gosearch -l regex -d 'regex mode'
complete -c gosearch -l follow-symlinks -d 'follow symlinks'
complete -c gosearch -l max-depth -r -d 'max traversal depth'
complete -c gosearch -l dynamic-workers -d 'dynamic cpu workers'
complete -c gosearch -l io-workers -r -d 'io worker count'
complete -c gosearch -l cpu-workers -r -d 'cpu worker count'
complete -c gosearch -l max-workers -r -d 'max cpu worker count'
complete -c gosearch -l backpressure -r -d 'channel buffer size'
complete -c gosearch -l metrics -d 'print metrics'
complete -c gosearch -l debug -d 'debug logs'
complete -c gosearch -l trace -d 'verbose trace'
complete -c gosearch -l monitor-goroutines -d 'monitor goroutines'
complete -c gosearch -l monitor-interval-ms -r -d 'monitor interval ms'
complete -c gosearch -l cpuprofile -r -d 'cpu profile output'
complete -c gosearch -l memprofile -r -d 'memory profile output'
complete -c gosearch -l config -r -d 'config file'
complete -c gosearch -l completion -r -a 'bash zsh fish' -d 'print completion script'
complete -c gosearch -l version -d 'print version'
